# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gpp-cmake:latest

stages:
  - build
before_script:
  - apt install libfreetype6-dev libjpeg-dev libx11-dev libxrandr-dev libsndfile1-dev libopenal-dev libgl1-mesa-glx -qq -y
  - cmake .

client:
  tags:
    - docker
  stage: build
  script:
    - cd Client
    - make

server:
  tags:
    - docker
  stage: build
  script:
    - cd Server
    - make
